apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-service
  labels:
    app: {{ .Chart.Name }}
    component: postgres
spec:
  ports:
    - port: {{ .Values.postgres.service.port }}
  selector:
    app: {{ .Chart.Name }}
    component: postgres
  clusterIP: None
