apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-service
  labels:
    app: {{ .Chart.Name }}
    component: web
spec:
  type: {{ .Values.web.service.type }}
  selector:
    app: {{ .Chart.Name }}
    component: web
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
